#!/usr/bin/env python3
import base64, sys, pathlib

root = pathlib.Path(__file__).resolve().parents[1]  # .../web

# Prefer embedded from web/stockfish; fallback to repo-level stockfish/
web_src = root / 'stockfish'
repo_src = pathlib.Path(__file__).resolve().parents[2] / 'stockfish'

def pick_source():
    cand = [web_src, repo_src]
    for c in cand:
        if (c / 'stockfish-16.1-lite.wasm').exists() and (c / 'stockfish-16.1-lite.js').exists():
            return c
    # If nothing found, raise with a helpful message
    raise FileNotFoundError(f"Could not find lite WASM/JS in {web_src} or {repo_src}. Did you copy assets? Try: mkdir -p web/stockfish && cp -a stockfish/. web/stockfish/")

src_dir = pick_source()
wasm = src_dir / 'stockfish-16.1-lite.wasm'
js = src_dir / 'stockfish-16.1-lite.js'

out_dir = root / 'src' / 'js' / 'embedded'
out_dir.mkdir(parents=True, exist_ok=True)
out = out_dir / 'stockfish-lite-embedded.js'

wb = wasm.read_bytes()
wb64 = base64.b64encode(wb).decode('ascii')
js_code = js.read_text(encoding='utf-8')

# Wrap in a worker that sets Module.wasmBinary then inlines engine JS
wrapper = f"""
// Auto-generated by scripts/embed_stockfish.py
export function createEmbeddedLiteWorker() {{
  const code = `\n    var Module = typeof Module !== 'undefined' ? Module : {{}};\n    try {{\n      var b64 = '{wb64}';\n      var raw = atob(b64);\n      var len = raw.length; var bytes = new Uint8Array(len);\n      for (var i=0;i<len;i++) bytes[i] = raw.charCodeAt(i);\n      Module.wasmBinary = bytes;\n      Module.locateFile = function(path) {{ return 'data:application/wasm;base64,' + b64; }};\n    }} catch(e) {{}}\n{js_code}\n  `;
  const blob = new Blob([code], {{ type: 'application/javascript' }});
  const url = URL.createObjectURL(blob);
  return new Worker(url);
}}
"""

out.write_text(wrapper, encoding='utf-8')
print(f"Embedded worker written to: {out}")
